# fly.toml app configuration file generated for silent-snow-6583 on 2023-08-01T09:14:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-snow-6583"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  [build.args]
    NODE_VERSION = "16.20.1"

[deploy]
  release_command = "npm run build"

[env]
  PORT = "8080"

[processes]
  app = "node app.js"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
