name: Periodic Health Check

on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  periodic_health_job:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: https://silent-snow-6583.fly.dev/
      - name: Discord notify Failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ github.event_name == 'pull_request' && failure() }}
        with:
          severity: error
          description: Periodic health check for https://silent-snow-6583.fly.dev/ failed.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord notify Success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ github.event_name == 'pull_request' && success() }}
        with:
          severity: info
          description: Periodic health check for https://silent-snow-6583.fly.dev/ was a success.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
